export const GITHUB_ICON =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/github_LDTcy1bc_.png?updatedAt=16886127797';
export const LINKEDIN_ICON =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/linkedin_aDQr6Huy2.png?updatedAt=16886127938';
export const CODE_ICON =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/code_2GKuQisNn.png?updatedAt=1697217597567';
export const CLOSE_MENU_ICON =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/close_eNQqVeiw3.png?updatedAt=1703309380667';
export const MENU_HAMBURGUER =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/hamburguer_1id8uhYeQ.png?updatedAt=1703307554746';
export const PAGINATION_ARROW = '/left.png';
export const PROFILE_PICTURE =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/profile-1_feYey8V23.jpeg?updatedAt=1712709533286';
export const PROFILE_CIRCLE = '/profile-circle.png';
export const META_TAG_IMAGE =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/capa_Lt5CpWfSYm.png?updatedAt=1707230740618';
export const FAVICON =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/binary-code_WBpGXnWnG.png?updatedAt=1700431546132';
export const POST_BACKGROUND_BLUR =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/blur-placeholder_Ab9CJ-nAf%201%202_jDOOWwKj3d.png?updatedAt=1733205516430';
export const POST_CONTENT_WRITER =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/profile_-roAsJAbQ.png?updatedAt=1688612357551';
export const PROJECTS_SLIDER_ARROW =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/arrow-white_bw7BBf49A.png?updatedAt=1705780260703';
export const HEART_GREEN =
  'https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/heart_ckLrCN-SF.svg';
export const HEART_WHITE = '/heart-white.png';
export const NEXT_JS_ICON = '/next.png';
export const REACT_JS_ICON = '/react.png';
export const TYPESCRIPT_ICON = '/typescript.png';
export const JAVASCRIPT_ICON = '/javascript.png';
export const STYLED_COMPONENTS_ICON = '/styled-components.png';
export const SASS_ICON = '/sass.png';
export const HTML_ICON = '/html.png';
export const CSS_ICON = '/css.png';
export const JEST_ICON = '/jest.png';
export const VERIFY_ICON = '/verify.png';
export const CLOSE_MODAL_ICON = '/error.png';
export const WHITE_LOADING_SPINNER = '/white-spinner.gif?v=3';
