import Head from 'next/head';
import { Fragment } from 'react';
import Header from '../components/layout/Header';
import { GetStaticProps } from 'next';
import Link from 'next/link';

export default function Home({ data }: any) {
    return (
        <Fragment>
            <Head>
                <title>My personal blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            {data.map((value: any, key: any) => {
                return (
                    <Link key={value.id} href={`Posts/${value.id}`}>
                        <div style={{ border: '1px solid red' }}>
                            <p>{value.title}</p>
                            <p>{value.post_text}</p>
                            <p>{value.user_name}</p>
                        </div>
                    </Link>
                );
            })}
        </Fragment>
    );
}

export interface MyComponentProps {
    data: any;
}

export const getStaticProps: GetStaticProps<MyComponentProps> = async () => {
    const response = await fetch('http://localhost:3001/api/get');
    const data = await response.json();

    return {
        props: {
            data,
        },
    };
};
