import React, { useState } from 'react';
import { Fragment } from 'react';
import Head from 'next/head';
import Profile from '@/components/Profile';
import 'aos/dist/aos.css';
import AOS from 'aos';
import { useEffect } from 'react';
import TechModal from '@/components/TechModal';
import techJson from '@/data/slider-tech.json';

interface TechInfo {
  name: string;
  description: string;
  link: string;
}

export const AboutMe = function () {
  const [showModal, setShowModal] = useState(false);
  const [currentModalTech, setCurrentModalTech] = useState({
    name: '',
    description: '',
    link: '',
  });

  useEffect(() => {
    AOS.init();
  }, []);

  const filterByName = (json: Record<string, TechInfo>, name: string) => {
    const keys = Object.keys(json);

    const filteredKeys = keys.filter(key => json[key].name.toLowerCase() === name.toLowerCase());

    return filteredKeys.map(key => json[key]);
  };

  const fetchTechDescription = async function (tech: string) {
    const filteredData = filterByName(techJson, tech);
    setCurrentModalTech({
      name: filteredData[0].name,
      description: filteredData[0].description,
      link: filteredData[0].link,
    });
  };

  const showTechInformationHandler = async function (arg: HTMLElement) {
    await fetchTechDescription(String(arg.getAttribute('data-tech')));
    setShowModal(true);
  };

  const closeModalHandler = function () {
    setShowModal(false);
  };

  return (
    <Fragment>
      <Head>
        <title>About me | blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Victor Lira" />
        <meta property="og:site_name" content="Victor Lira" />
        <link
          rel="icon"
          href="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/binary-code_WBpGXnWnG.png?updatedAt=1700431546132"
        />
        <meta
          property="og:image"
          content="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/capa_Lt5CpWfSYm.png?updatedAt=1707230740618"
        />
      </Head>
      <TechModal
        techName={currentModalTech.name}
        techDescription={currentModalTech.description}
        techLink={currentModalTech.link}
        className={showModal ? 'active' : ''}
        closeModal={closeModalHandler}
      />
      <Profile className="profile" onShowTechInformationHandler={showTechInformationHandler} />
    </Fragment>
  );
};
