export const lightTheme = {
  body: '#ededed',
  cardBody: '#fff',
  fontColor: '#000',
  cardBorder: 'none',
  cardBoxShadow: '1px 3px 10px 1px #ccc',
  cardBorderRadius: '10px',
  cardColor: '#000',
  cardSecudaryColor: '#204c97',
  aboutBackground: '#362692',
  footerBackground: '#362692',
  profileBorder: 'none',
  profileBoxShadow: '1px 3px 10px 1px #ccc',
  headerBackground: '#362692',
  headerColor: '#fff',
  headerDropdownMenu: '#4836af',
  profileSecudaryColor: '#5c47d6',
  profileBorderCardImage: '1px solid #ccc',
  profileBoxShadowCardImage: '0px 0px 10px 0px #837f7f',
  profileDownloadResumeButton: '2px solid #5c47d6',
  profileDownloadBackground: '#5c47d6',
  profileDownloadColor: '#fff',
  techSliderText: '#000',
  techSliderDots: '#000',
  techSliderDotActive: '#5c47d6',
  countryBoxShadow: '1px 3px 5px 1px #d3d3d3',
  profileDownloadResumeBoxShadow: '1px 3px 5px 1px #d3d3d3',

  bodyPostColor: '#000',
  bodyPostWriterBorderColor: 'none',
  bodyPostMainWriterBorderColor: 'none',
  bodyPostImageBackground: '#eeeeee',
};

export const darkTheme = {
  body: '#121212',
  cardBody: '#',
  fontColor: '#fff',
  cardBorder: '1px solid #0497EF',
  cardBoxShadow: '0px 0px 10px 0px #0497EF',
  cardBorderRadius: '10px',
  cardColor: '#b4b4b4',
  cardSecudaryColor: '#9ec0fa',
  aboutBackground: '#020709',
  footerBackground: '#080808',
  profileBorder: '2px solid #1f1f1f',
  profileBoxShadow: 'none',
  headerBackground: '#121212',
  headerColor: '#fff',
  headerDropdownMenu: '#181818',
  profileSecudaryColor: '#0beeb2',
  profileBorderCardImage: '1px solid rgb(11, 238, 178)',
  profileBoxShadowCardImage: '0px 0px 10px 0px rgb(11, 238, 178)',
  profileDownloadResumeButton: '2px solid #0beeb2',
  profileDownloadBackground: 'transparent',
  profileDownloadColor: '#0beeb2',
  techSliderText: '#fff',
  techSliderDots: '#fff',
  techSliderDotActive: '#0beeb2',
  countryBoxShadow: 'none',
  profileDownloadResumeBoxShadow: 'none',
  bodyPostColor: '#fff',
  bodyPostWriterBorderColor: '#141920',
  bodyPostMainWriterBorderColor: '#0497EF',
  bodyPostImageBackground: '#202020',
};
