import React from 'react';
import { Fragment } from 'react';
import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Profile from '@/components/Profile';

const AboutMe = function () {
    return (
        <Fragment>
            <Head>
                <title>About me | blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <meta name="author" content="Victor Lira" />
                <meta property="og:site_name" content="Victor Lira" />
                <link
                    rel="icon"
                    href="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/binary-code_WBpGXnWnG.png?updatedAt=1700431546132"
                />
                <meta
                    property="og:image"
                    content="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/capa_Lt5CpWfSYm.png?updatedAt=1707230740618"
                />
            </Head>
            <Header />
            <Profile />
            <Footer />
        </Fragment>
    );
};

export default AboutMe;
