import React from 'react';
import { Fragment } from 'react';
import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Profile from '@/components/Profile';
import 'aos/dist/aos.css';
import AOS from 'aos';
import { useEffect } from 'react';
import { lightTheme, darkTheme } from '../../theme';
import { ThemeProvider } from 'styled-components';
import { GlobalStyled } from '@/GlobalStyles';
import { ThemeContainer } from '@/ThemeContainer.styled';
import { useTheme } from '@/Context/darkmode';
import { useScrollContext } from '@/Context/scrollProvider';

const AboutMe = function () {
  const { scrollIntoViewHandler } = useScrollContext();
  const { theme, toggleTheme } = useTheme();

  useEffect(() => {
    AOS.init();
  }, []);

  const themeToggler = function () {
    toggleTheme();
  };

  return (
    <Fragment>
      <Head>
        <title>About me | blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Victor Lira" />
        <meta property="og:site_name" content="Victor Lira" />
        <link
          rel="icon"
          href="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/binary-code_WBpGXnWnG.png?updatedAt=1700431546132"
        />
        <meta
          property="og:image"
          content="https://ik.imagekit.io/Victorliradev/blog_pessoal/assets/capa_Lt5CpWfSYm.png?updatedAt=1707230740618"
        />
      </Head>
      <ThemeProvider theme={theme === 'light' ? lightTheme : darkTheme}>
        <GlobalStyled />
        <ThemeContainer>
          <Header
            className="header"
            theme={theme}
            themeToggler={() => themeToggler()}
            scrollIntoView={() => scrollIntoViewHandler()}
          />
          <Profile className="profile" />
          <Footer />
        </ThemeContainer>
      </ThemeProvider>
    </Fragment>
  );
};

export default AboutMe;
